# Generated by Django 4.0.3 on 2022-06-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='fhir_id',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
