# Generated by Django 4.0.3 on 2022-06-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_management', '0003_alter_department_fhir_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='fhir_practitioner_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='practice_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
