# Generated by Django 4.0.3 on 2022-07-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ward_management', '0002_ward_fhir_location_id'),
        ('doctor_management', '0004_doctor_fhir_practitioner_id_doctor_practice_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='location',
            field=models.ManyToManyField(blank=True, related_name='doctor_location', to='ward_management.ward'),
        ),
    ]
