# Generated by Django 4.0.2 on 2022-02-11 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Insurance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CapitationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_of_contribution', models.CharField(blank=True, max_length=100, null=True)),
                ('weight_of_population', models.CharField(blank=True, max_length=100, null=True)),
                ('weight_of_number_of_families', models.CharField(blank=True, max_length=100, null=True)),
                ('weight_of_insured_population', models.CharField(blank=True, max_length=100, null=True)),
                ('weight_of_insured_families', models.CharField(blank=True, max_length=100, null=True)),
                ('weight_of_number_of_visits', models.CharField(blank=True, max_length=100, null=True)),
                ('weight_of_adjusted_amount', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CareType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ceiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation', models.CharField(blank=True, max_length=100, null=True)),
                ('surgeries', models.CharField(blank=True, max_length=100, null=True)),
                ('deliveries', models.CharField(blank=True, max_length=100, null=True)),
                ('hospitalization', models.CharField(blank=True, max_length=100, null=True)),
                ('antenatal', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('0', 'NONE'), ('1', 'MONTHLY'), ('2', 'QUATERLY'), ('3', 'YEARLY')], default='0', max_length=1)),
                ('month_1', models.CharField(blank=True, max_length=100, null=True)),
                ('month_2', models.CharField(blank=True, max_length=100, null=True)),
                ('month_3', models.CharField(blank=True, max_length=100, null=True)),
                ('month_4', models.CharField(blank=True, max_length=100, null=True)),
                ('month_5', models.CharField(blank=True, max_length=100, null=True)),
                ('month_6', models.CharField(blank=True, max_length=100, null=True)),
                ('month_7', models.CharField(blank=True, max_length=100, null=True)),
                ('month_8', models.CharField(blank=True, max_length=100, null=True)),
                ('month_9', models.CharField(blank=True, max_length=100, null=True)),
                ('month_10', models.CharField(blank=True, max_length=100, null=True)),
                ('month_11', models.CharField(blank=True, max_length=100, null=True)),
                ('month_12', models.CharField(blank=True, max_length=100, null=True)),
                ('quater_1', models.CharField(blank=True, max_length=100, null=True)),
                ('quater_2', models.CharField(blank=True, max_length=100, null=True)),
                ('quater_3', models.CharField(blank=True, max_length=100, null=True)),
                ('quater_4', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraMemberCeiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceiling', models.CharField(blank=True, max_length=100, null=True)),
                ('hospital_ceiling', models.CharField(blank=True, max_length=100, null=True)),
                ('non_hospital_ceiling', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthFacilityLegalForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthFacilitySubLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insuree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deductible', models.CharField(blank=True, max_length=100, null=True)),
                ('ceiling', models.CharField(blank=True, max_length=100, null=True)),
                ('hospital_deductible', models.CharField(blank=True, max_length=100, null=True)),
                ('hospital_ceiling', models.CharField(blank=True, max_length=100, null=True)),
                ('non_hospital_deductible', models.CharField(blank=True, max_length=100, null=True)),
                ('non_hospital_ceiling', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaximumCeiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceiling', models.CharField(blank=True, max_length=100, null=True)),
                ('hospital_ceiling', models.CharField(blank=True, max_length=100, null=True)),
                ('non_hospital_ceiling', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.BigIntegerField(blank=True, null=True)),
                ('frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('male', models.BooleanField(default=True)),
                ('female', models.BooleanField(default=True)),
                ('adult', models.BooleanField(default=True)),
                ('minor', models.BooleanField(default=True)),
                ('care_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_administration.caretype')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_administration.itemtype')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.BigIntegerField(blank=True, null=True)),
                ('frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('male', models.BooleanField(default=True)),
                ('female', models.BooleanField(default=True)),
                ('adult', models.BooleanField(default=True)),
                ('minor', models.BooleanField(default=True)),
                ('care_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_administration.caretype')),
            ],
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation', models.CharField(blank=True, max_length=100, null=True)),
                ('surgeries', models.CharField(blank=True, max_length=100, null=True)),
                ('deliveries', models.CharField(blank=True, max_length=100, null=True)),
                ('hospitalization', models.CharField(blank=True, max_length=100, null=True)),
                ('antenatal', models.CharField(blank=True, max_length=100, null=True)),
                ('visits', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deductible', models.CharField(blank=True, max_length=100, null=True)),
                ('ceiling', models.CharField(blank=True, max_length=100, null=True)),
                ('hospital_deductible', models.CharField(blank=True, max_length=100, null=True)),
                ('hospital_ceiling', models.CharField(blank=True, max_length=100, null=True)),
                ('non_hospital_deductible', models.CharField(blank=True, max_length=100, null=True)),
                ('non_hospital_ceiling', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesPriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deductible', models.CharField(blank=True, max_length=100, null=True)),
                ('ceiling', models.CharField(blank=True, max_length=100, null=True)),
                ('hospital_deductible', models.CharField(blank=True, max_length=100, null=True)),
                ('hospital_ceiling', models.CharField(blank=True, max_length=100, null=True)),
                ('non_hospital_deductible', models.CharField(blank=True, max_length=100, null=True)),
                ('non_hospital_ceiling', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('lump_sum', models.BigIntegerField(blank=True, null=True)),
                ('threshold_member', models.CharField(blank=True, max_length=100, null=True)),
                ('maximum_memebers', models.BigIntegerField(blank=True, null=True)),
                ('contribution_adult', models.CharField(blank=True, max_length=100, null=True)),
                ('contribution_child', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance_period', models.IntegerField(blank=True, null=True)),
                ('administration_period', models.IntegerField(blank=True, null=True)),
                ('max_installments', models.IntegerField(blank=True, null=True)),
                ('grace_period_payment', models.IntegerField(blank=True, null=True)),
                ('grace_period_enrollment', models.IntegerField(blank=True, null=True)),
                ('grace_period_renewal', models.IntegerField(blank=True, null=True)),
                ('renewal_disc', models.IntegerField(blank=True, null=True)),
                ('renewal_disc_period', models.IntegerField(blank=True, null=True)),
                ('enrollment_disc', models.IntegerField(blank=True, null=True)),
                ('enrollment_disc_period', models.IntegerField(blank=True, null=True)),
                ('account_code_remuneration', models.CharField(blank=True, max_length=100, null=True)),
                ('account_code_contribution', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_lump_sum', models.BigIntegerField(blank=True, null=True)),
                ('assembly_lump_sum', models.BigIntegerField(blank=True, null=True)),
                ('registration_fee', models.BigIntegerField(blank=True, null=True)),
                ('assembly_fee', models.BigIntegerField(blank=True, null=True)),
                ('start_cycle_1_day', models.IntegerField(blank=True, null=True)),
                ('start_cycle_1_month', models.IntegerField(blank=True, null=True)),
                ('start_cycle_2_day', models.IntegerField(blank=True, null=True)),
                ('start_cycle_2_month', models.IntegerField(blank=True, null=True)),
                ('start_cycle_3_day', models.IntegerField(blank=True, null=True)),
                ('start_cycle_3_month', models.IntegerField(blank=True, null=True)),
                ('start_cycle_4_day', models.IntegerField(blank=True, null=True)),
                ('start_cycle_4_month', models.IntegerField(blank=True, null=True)),
                ('capitation_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_administration.capitationpayment')),
                ('conversion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_administration.conversion')),
                ('distribution_deductable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deductable', to='insurance_administration.distribution')),
                ('distribution_deductable_hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deductablehospital', to='insurance_administration.distribution')),
                ('distribution_deductable_non_hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deductablenonhospital', to='insurance_administration.distribution')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_administration.district')),
                ('extra_member_ceiling', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_administration.extramemberceiling')),
                ('insuree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_administration.insuree')),
                ('maximum_ceiling', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_administration.maximumceiling')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_administration.policy')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_administration.region')),
                ('treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_administration.treatment')),
            ],
        ),
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('fax', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_administration.district')),
                ('payer_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_administration.payertype')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_administration.region')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalServicesPriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_administration.district')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_administration.region')),
                ('services', models.ManyToManyField(related_name='services', to='insurance_administration.MedicalServices')),
            ],
        ),
        migrations.AddField(
            model_name='medicalservices',
            name='service_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_administration.servicecategory'),
        ),
        migrations.AddField(
            model_name='medicalservices',
            name='service_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_administration.servicelevel'),
        ),
        migrations.AddField(
            model_name='medicalservices',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_administration.servicetype'),
        ),
        migrations.CreateModel(
            name='MedicalItemsPriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_administration.district')),
                ('items', models.ManyToManyField(related_name='services', to='insurance_administration.MedicalItem')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_administration.region')),
            ],
        ),
        migrations.CreateModel(
            name='HealthFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('accounting_code', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('fax', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('care_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_administration.caretype')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_administration.district')),
                ('health_facility_legal_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_administration.healthfacilitylegalform')),
                ('health_facility_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.healthfacilitylevel')),
                ('health_facility_sub_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_administration.healthfacilitysublevel')),
                ('item_price_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_administration.itempricelist')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_administration.region')),
                ('services_price_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_administration.servicespricelist')),
            ],
        ),
        migrations.CreateModel(
            name='ContributionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('periodically', models.IntegerField(blank=True, null=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('calculation_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_administration.calculationrules')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_administration.product')),
            ],
        ),
        migrations.AddField(
            model_name='capitationpayment',
            name='level_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_1', to='insurance_administration.level'),
        ),
        migrations.AddField(
            model_name='capitationpayment',
            name='level_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_2', to='insurance_administration.level'),
        ),
        migrations.AddField(
            model_name='capitationpayment',
            name='level_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_3', to='insurance_administration.level'),
        ),
        migrations.AddField(
            model_name='capitationpayment',
            name='level_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_4', to='insurance_administration.level'),
        ),
        migrations.AddField(
            model_name='capitationpayment',
            name='sub_level_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_level_1', to='insurance_administration.sublevel'),
        ),
        migrations.AddField(
            model_name='capitationpayment',
            name='sub_level_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_level_2', to='insurance_administration.sublevel'),
        ),
        migrations.AddField(
            model_name='capitationpayment',
            name='sub_level_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_level_3', to='insurance_administration.sublevel'),
        ),
        migrations.AddField(
            model_name='capitationpayment',
            name='sub_level_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_level_4', to='insurance_administration.sublevel'),
        ),
    ]
