# Generated by Django 4.0.3 on 2022-06-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ward_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='fhir_location_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
