# Generated by Django 4.0.2 on 2022-02-11 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurance_administration', '0001_initial'),
        ('Insurance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('explaination', models.CharField(blank=True, max_length=1000, null=True)),
                ('medical_items', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_administration.medicalitem')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('explaination', models.CharField(blank=True, max_length=1000, null=True)),
                ('medical_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_administration.medicalservices')),
            ],
        ),
        migrations.CreateModel(
            name='Claims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date_from', models.DateField(blank=True, null=True)),
                ('visit_date_to', models.DateField(blank=True, null=True)),
                ('claimed_date', models.DateField(blank=True, null=True)),
                ('visit_type', models.CharField(choices=[('ANY', 'ANY'), ('EMERGENCY', 'EMERGENCY'), ('OTHER', 'OTHER'), ('REFERAL', 'REFERAL')], default='ANY', max_length=20)),
                ('claim_num', models.CharField(blank=True, max_length=100, null=True)),
                ('guarantee_num', models.CharField(blank=True, max_length=100, null=True)),
                ('claimed_amount', models.IntegerField(blank=True, null=True)),
                ('explaination', models.CharField(blank=True, max_length=1000, null=True)),
                ('claim_status', models.CharField(choices=[('ANY', 'ANY'), ('ENTERED', 'ENTERED'), ('REJECTED', 'REJECTED'), ('CHECKED', 'CHECKED'), ('PROCESSED', 'PROCESSED'), ('VALUATED', 'VALUATED')], default='ANY', max_length=20)),
                ('feedback_status', models.CharField(choices=[('NOT SELECTED', 'NOT SELECTED'), ('SELECTED', 'SELECTED'), ('DELIVERED', 'DELIVERED'), ('BYPASSED', 'BYPASSED')], default='SELECTED', max_length=20)),
                ('review_status', models.CharField(choices=[('NOT SELECTED', 'NOT SELECTED'), ('SELECTED', 'SELECTED'), ('BYPASSED', 'BYPASSED')], default='SELECTED', max_length=20)),
                ('submitted', models.BooleanField(default=False)),
                ('claim_administrator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.insuranceuser')),
                ('health_facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_administration.healthfacilities')),
                ('insurance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Insurance.headinsuree')),
                ('main_diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_diagnosis', to='Insurance.diagnosis')),
                ('medical_items', models.ManyToManyField(related_name='claims_medical_items', to='claims.ClaimItems')),
                ('medical_services', models.ManyToManyField(related_name='claims_medical_services', to='claims.ClaimServices')),
                ('seg_dg_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seg_dg_1', to='Insurance.diagnosis')),
                ('seg_dg_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seg_dg_2', to='Insurance.diagnosis')),
                ('seg_dg_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seg_dg_3', to='Insurance.diagnosis')),
                ('seg_dg_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seg_dg_4', to='Insurance.diagnosis')),
            ],
        ),
    ]
