# Generated by Django 4.0.2 on 2022-02-11 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic_management', '0001_initial'),
        ('Patient', '0001_initial'),
        ('doctor_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.CharField(max_length=10, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderAvail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('time_slot_length', models.CharField(blank=True, max_length=100, null=True)),
                ('available_types', models.ManyToManyField(related_name='available_types', to='schedule_management.AppointmentType')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider', to='doctor_management.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_avail', to='schedule_management.provideravail')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('checkin', models.DateTimeField(blank=True, null=True)),
                ('checkout', models.DateTimeField(blank=True, null=True)),
                ('clinic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_management.clinic')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.patient')),
                ('slot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot', to='schedule_management.slot')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule_management.appointmenttype')),
            ],
        ),
    ]
