# Generated by Django 4.0.2 on 2022-02-11 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ward_management', '0001_initial'),
        ('doctor_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_residence', models.CharField(blank=True, max_length=500, null=True)),
                ('off', models.CharField(blank=True, max_length=500, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True)),
                ('Int_Mob', models.BooleanField(default=False)),
                ('Fax', models.CharField(blank=True, max_length=500, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=13, null=True)),
                ('send_email', models.BooleanField(default=False)),
                ('send_sms', models.BooleanField(default=False)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('p_o_box', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('willing_to_donate_blood', models.BooleanField(default=False)),
                ('emergency_patient', models.BooleanField(default=False)),
                ('require_data_update', models.BooleanField(default=False)),
                ('last_modification_date', models.DateTimeField(blank=True, null=True)),
                ('modified_user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('CLOSED', 'CLOSED'), ('HOLD', 'HOLD')], max_length=6, null=True)),
                ('stop_ivr', models.BooleanField(default=False)),
                ('permanent_address', models.CharField(blank=True, max_length=500, null=True)),
                ('temporary_address', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('identification_type', models.CharField(choices=[('NATIONAL-ID', 'NATIONAL-ID'), ('IQAMA', 'IQAMA'), ('NON ID', 'NON ID')], max_length=14, null=True)),
                ('account_id', models.CharField(max_length=50, null=True)),
                ('registeration_date', models.DateTimeField(auto_now_add=True)),
                ('relationship_type', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=1, null=True)),
                ('id_number', models.IntegerField(null=True)),
                ('registeration_type', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=1, null=True)),
                ('health_id', models.IntegerField(null=True)),
                ('id_expiry', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(default='M', max_length=17, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('second_name', models.CharField(blank=True, max_length=50, null=True)),
                ('third_name', models.CharField(blank=True, max_length=50, null=True)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('first_name_arabic', models.CharField(blank=True, max_length=50, null=True)),
                ('second_name_arabic', models.CharField(blank=True, max_length=50, null=True)),
                ('thrid_name_arabic', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name_arabic', models.CharField(blank=True, max_length=50, null=True)),
                ('blood_group', models.CharField(max_length=3, null=True)),
                ('rh_facto', models.CharField(max_length=3, null=True)),
                ('maritail_status', models.CharField(blank=True, max_length=1, null=True)),
                ('DOB_hijri', models.CharField(blank=True, max_length=50, null=True)),
                ('pregnant', models.BooleanField(default=False)),
                ('privilage_member', models.BooleanField(default=False)),
                ('membership_num', models.CharField(blank=True, max_length=50, null=True)),
                ('file_type', models.FileField(blank=True, null=True, upload_to='')),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.contactinformation')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor_management.department')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('discharge_criteria', models.CharField(choices=[('N', 'NONE'), ('1', 'ONLY DISPLAY PATIENTS THAT ARE NOT DISCHARGE')], max_length=4)),
                ('active', models.BooleanField(default=False)),
                ('location', models.ManyToManyField(related_name='location', to='ward_management.Ward')),
                ('patient', models.ManyToManyField(related_name='patients', to='Patient.Patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
