# Generated by Django 4.0.3 on 2022-03-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0002_alter_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='deceasedBoolean',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='deceasedDateTime',
            field=models.DateTimeField(null=True),
        ),
    ]
