# Generated by Django 4.0.3 on 2022-03-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0004_rename_privilage_member_patient_privilege_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinformation',
            name='emergency_contact_gender',
            field=models.CharField(max_length=17, null=True),
        ),
    ]
