# Generated by Django 4.0.3 on 2022-03-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0005_contactinformation_emergency_contact_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinformation',
            name='emergency_contact_relationship',
            field=models.CharField(max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='emergency_contact_gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other'), ('unknown', 'unknown')], max_length=17, null=True),
        ),
    ]
