# Generated by Django 4.0.3 on 2022-03-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0006_contactinformation_emergency_contact_relationship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(max_length=17, null=True),
        ),
    ]
