# Generated by Django 4.0.3 on 2022-06-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0007_alter_patient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='deceasedDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
