# Generated by Django 4.0.3 on 2022-06-20 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0008_alter_patient_deceaseddatetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='patient_id',
            new_name='document_id',
        ),
    ]
