# Generated by Django 4.0.3 on 2022-06-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0010_patient_document_type_patient_e_health_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinformation',
            name='email',
            field=models.EmailField(blank=True, max_length=500, null=True),
        ),
    ]
