# Generated by Django 4.0.3 on 2022-06-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0012_remove_patient_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='fhir_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
