# Generated by Django 4.0.3 on 2022-06-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0013_patient_fhir_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='third_name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
