# Generated by Django 4.0.3 on 2022-06-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0014_alter_patient_third_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='third_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
