# Generated by Django 4.0.3 on 2022-03-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0002_alter_headinsuree_maritial_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headinsuree',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other'), ('unknown', 'unknown')], max_length=7, null=True),
        ),
    ]
