# Generated by Django 4.0.2 on 2022-02-11 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPTITEM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HCPCS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ICD10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ICD9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnsetDataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtherDateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(null=True)),
                ('note', models.CharField(blank=True, max_length=1000, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule_management.appointment')),
                ('method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.paymentmethod')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.paymenttype')),
            ],
        ),
        migrations.CreateModel(
            name='HCPCSCODE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(null=True)),
                ('diagnosis_pointer', models.FloatField(null=True)),
                ('price', models.FloatField(null=True)),
                ('hcpcs_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.hcpcs')),
            ],
        ),
        migrations.CreateModel(
            name='HcfaBOX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employement', models.BooleanField(default=False)),
                ('auto_accident', models.BooleanField(default=False)),
                ('other_accident', models.BooleanField(default=False)),
                ('onset_date', models.DateField(blank=True, null=True)),
                ('other_date', models.DateField(blank=True, null=True)),
                ('one_set_data_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.onsetdatatype')),
                ('other_date_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.otherdatetype')),
            ],
        ),
        migrations.CreateModel(
            name='CPTCODE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(null=True)),
                ('diagnosis_pointer', models.FloatField(null=True)),
                ('price', models.FloatField(null=True)),
                ('cpt_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.cptitem')),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icd_version', models.CharField(choices=[('AUTO', 'AUTO'), ('ICD-10', 'ICD-10'), ('ICD-9', 'ICD-9')], default='AUTO', max_length=10)),
                ('pre_authorization_approval', models.CharField(blank=True, max_length=100, null=True)),
                ('refferal_num', models.CharField(blank=True, max_length=100, null=True)),
                ('cpt_code', models.ManyToManyField(related_name='cpt_codes', to='billing.CPTCODE')),
                ('hcfa_box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.hcfabox')),
                ('hcpcs_code', models.ManyToManyField(related_name='cpt_codes', to='billing.HCPCSCODE')),
                ('icd_10', models.ManyToManyField(related_name='icd_10', to='billing.ICD10')),
                ('icd_9', models.ManyToManyField(related_name='icd_9', to='billing.ICD9')),
                ('payment', models.ManyToManyField(related_name='billing_payment', to='billing.Payment')),
                ('payment_profile', models.ManyToManyField(related_name='payment_profile', to='billing.PaymentProfile')),
            ],
        ),
    ]
