# Generated by Django 4.0.2 on 2022-02-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='status',
            field=models.CharField(blank=True, choices=[('Paid In Full', 'Paid In Full'), ('Balance Due', 'Balance Due'), ('Settled', 'Settled'), ('Internal Review', 'Internal Review'), ('Bill Insurance', 'Bill Insurance'), ('Bill Secondary Insurance', 'Bill Secondary Insurance'), ("Worker's Comp Claim", "Worker's Comp Claim"), ('Auto Accident Claim', 'Auto Accident Claim'), ('Durable Medical Equipment Claim', 'Durable Medical Equipment Claim')], max_length=50, null=True),
        ),
    ]
