# Generated by Django 4.0.2 on 2022-02-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_billing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
