# Generated by Django 4.0.3 on 2022-05-21 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_management', '0001_initial'),
        ('billing', '0007_alter_payment_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='payment',
        ),
        migrations.AddField(
            model_name='billing',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule_management.appointment'),
        ),
    ]
