# Generated by Django 4.0.3 on 2022-05-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_remove_billing_payment_billing_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='fhir_claim_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
