# Generated by Django 4.0.3 on 2022-05-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_billing_fhir_claim_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
