# Generated by Django 4.0.3 on 2022-06-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_billing_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='bundle_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
