# Generated by Django 4.0.3 on 2022-06-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_rename_bundle_id_billing_eligibility_request_bundle_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='eligibility_response',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='eligibility_response_status',
            field=models.BooleanField(default=False),
        ),
    ]
