# Generated by Django 4.0.3 on 2022-06-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_billing_eligibility_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cptitem',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='icd10',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
