# Generated by Django 4.0.3 on 2022-06-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_cptitem_price_icd10_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hcpcscode',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
