# Generated by Django 4.0.3 on 2022-06-10 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_remove_hcpcscode_diagnosis_pointer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cptcode',
            name='diagnosis_pointer',
        ),
        migrations.RemoveField(
            model_name='cptcode',
            name='price',
        ),
    ]
