# Generated by Django 4.0.3 on 2022-06-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_remove_cptcode_diagnosis_pointer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cptcode',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
