# Generated by Django 4.0.3 on 2022-06-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_alter_cptcode_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='icd_9',
        ),
        migrations.AlterField(
            model_name='billing',
            name='hcpcs_code',
            field=models.ManyToManyField(related_name='hcpcs_codes', to='billing.hcpcscode'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='payment_profile',
            field=models.ManyToManyField(blank=True, related_name='payment_profile', to='billing.paymentprofile'),
        ),
    ]
