# Generated by Django 4.0.3 on 2022-06-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_remove_billing_icd_9_alter_billing_hcpcs_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='claim_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='paid_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
