# Generated by Django 4.0.3 on 2022-06-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_billing_claim_amount_billing_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='unit_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
