# Generated by Django 4.0.3 on 2022-06-14 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FHIR', '0001_initial'),
        ('billing', '0021_billing_unit_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='eligibility_request_bundle_id',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='eligibility_response',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='eligibility_response_status',
        ),
        migrations.AddField(
            model_name='billing',
            name='claim_bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FHIR.claimbundle'),
        ),
        migrations.AddField(
            model_name='billing',
            name='communication_bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FHIR.communicationbundle'),
        ),
        migrations.AddField(
            model_name='billing',
            name='eligibility_bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FHIR.coverageeligibilitybundle'),
        ),
        migrations.AddField(
            model_name='billing',
            name='payment_notice_bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FHIR.paymentnoticebundle'),
        ),
        migrations.AddField(
            model_name='billing',
            name='payment_reconciliation_bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FHIR.paymentreconciliationbundle'),
        ),
        migrations.AddField(
            model_name='billing',
            name='pre_auth_bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FHIR.preauthbundle'),
        ),
    ]
