# Generated by Django 4.0.3 on 2022-06-14 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0023_billing_payment_cancel_bundle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='payment_cancel_bundle',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='payment_poll_bundle',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='payment_status_bundle',
        ),
    ]
