# Generated by Django 4.0.3 on 2022-06-14 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FHIR', '0003_taskbundle'),
        ('billing', '0024_remove_billing_payment_cancel_bundle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='payment_cancel_bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancel_bundle', to='FHIR.taskbundle'),
        ),
        migrations.AddField(
            model_name='billing',
            name='payment_poll_bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poll_bundle', to='FHIR.taskbundle'),
        ),
        migrations.AddField(
            model_name='billing',
            name='payment_status_bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_bundle', to='FHIR.taskbundle'),
        ),
    ]
