# Generated by Django 4.0.2 on 2022-02-11 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ward_management', '0001_initial'),
        ('administration', '0001_initial'),
        ('Patient', '0001_initial'),
        ('Patient_health_record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='lab_result',
            field=models.ManyToManyField(related_name='Encounter_tests', to='administration.TestResult'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ward_management.ward'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient_health_record.order'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.patient'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='physical_exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient_health_record.physicalexam'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='problem_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient_health_record.problemlist'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='progress_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient_health_record.progressnote'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='relationship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient_health_record.relationship'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='review_of_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient_health_record.reviewofsystem'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient_health_record.encountertype'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='vital_sign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient_health_record.vitalsigns'),
        ),
        migrations.AddField(
            model_name='assessmentandplan',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient_health_record.problemlist'),
        ),
    ]
