# Generated by Django 4.0.3 on 2022-06-11 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_management', '0001_initial'),
        ('Patient_health_record', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encounter',
            name='location',
        ),
        migrations.RemoveField(
            model_name='encounter',
            name='relationship',
        ),
        migrations.AddField(
            model_name='encounter',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule_management.appointment'),
        ),
    ]
