# Generated by Django 4.0.3 on 2022-06-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_alter_resultlimit_gender'),
        ('Patient_health_record', '0004_remove_encounter_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='assessment_and_plan',
            field=models.ManyToManyField(blank=True, related_name='encounter_AssessmentAndPlan', to='Patient_health_record.assessmentandplan'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='document',
            field=models.ManyToManyField(blank=True, related_name='Encounter_documents', to='Patient_health_record.document'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='history',
            field=models.ManyToManyField(blank=True, related_name='Encounter_history', to='Patient_health_record.history'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='home_medication',
            field=models.ManyToManyField(blank=True, related_name='Encounter_home_medication', to='Patient_health_record.dosageinstruction'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='lab_result',
            field=models.ManyToManyField(blank=True, related_name='Encounter_tests', to='administration.testresult'),
        ),
    ]
