# Generated by Django 4.0.3 on 2022-06-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient_health_record', '0005_alter_encounter_assessment_and_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encounter',
            name='vital_sign',
        ),
        migrations.AddField(
            model_name='encounter',
            name='vital_sign',
            field=models.ManyToManyField(blank=True, to='Patient_health_record.vitalsigns'),
        ),
    ]
