# Generated by Django 4.0.3 on 2022-06-11 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient_health_record', '0006_remove_encounter_vital_sign_encounter_vital_sign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vitalsigns',
            old_name='name',
            new_name='code',
        ),
    ]
