# Generated by Django 4.0.3 on 2022-06-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient_health_record', '0007_rename_name_vitalsigns_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
