# Generated by Django 4.0.3 on 2022-06-14 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_bundle_id', models.CharField(blank=True, max_length=100, null=True)),
                ('request_bundle', models.JSONField(blank=True, null=True)),
                ('claim_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('response_bundle_id', models.CharField(blank=True, max_length=100, null=True)),
                ('response_bundle_status', models.BooleanField(default=False)),
                ('response_bundle', models.JSONField(blank=True, null=True)),
                ('claim_response_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_bundle_id', models.CharField(blank=True, max_length=100, null=True)),
                ('request_bundle', models.JSONField(blank=True, null=True)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('communication_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('response_bundle_id', models.CharField(blank=True, max_length=100, null=True)),
                ('response_bundle_status', models.BooleanField(default=False)),
                ('response_bundle', models.JSONField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('communication_response_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoverageEligibilityBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_bundle_id', models.CharField(blank=True, max_length=100, null=True)),
                ('request_bundle', models.JSONField(blank=True, null=True)),
                ('eligibility_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('response_bundle_id', models.CharField(blank=True, max_length=100, null=True)),
                ('response_bundle_status', models.BooleanField(default=False)),
                ('response_bundle', models.JSONField(blank=True, null=True)),
                ('eligibility_response_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentNoticeBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_bundle_id', models.CharField(blank=True, max_length=100, null=True)),
                ('request_bundle', models.JSONField(blank=True, null=True)),
                ('payment_reconciliation_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentReconciliationBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_bundle_id', models.CharField(blank=True, max_length=100, null=True)),
                ('request_bundle', models.JSONField(blank=True, null=True)),
                ('claim_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_reconciliation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('claim_response_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreAuthBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_bundle_id', models.CharField(blank=True, max_length=100, null=True)),
                ('request_bundle', models.JSONField(blank=True, null=True)),
                ('pre_auth_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('response_bundle_status', models.BooleanField(default=False)),
                ('response_bundle_id', models.CharField(blank=True, max_length=100, null=True)),
                ('response_bundle', models.JSONField(blank=True, null=True)),
                ('claim_response_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_bundle_id', models.CharField(blank=True, max_length=100, null=True)),
                ('request_bundle', models.JSONField(blank=True, null=True)),
                ('request_task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('response_bundle_id', models.CharField(blank=True, max_length=100, null=True)),
                ('response_bundle', models.JSONField(blank=True, null=True)),
                ('response_task_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
