# Generated by Django 4.0.3 on 2022-06-14 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FHIR', '0002_delete_taskbundle'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_bundle_id', models.CharField(blank=True, max_length=100, null=True)),
                ('request_bundle', models.JSONField(blank=True, null=True)),
                ('request_task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('response_bundle_id', models.CharField(blank=True, max_length=100, null=True)),
                ('response_bundle', models.JSONField(blank=True, null=True)),
                ('response_task_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
