# Generated by Django 4.0.3 on 2022-06-26 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0015_alter_patient_third_name'),
        ('FHIR', '0003_taskbundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimbundle',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.patient'),
        ),
        migrations.AddField(
            model_name='communicationbundle',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.patient'),
        ),
        migrations.AddField(
            model_name='coverageeligibilitybundle',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.patient'),
        ),
        migrations.AddField(
            model_name='paymentnoticebundle',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.patient'),
        ),
        migrations.AddField(
            model_name='paymentreconciliationbundle',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.patient'),
        ),
        migrations.AddField(
            model_name='preauthbundle',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.patient'),
        ),
        migrations.AddField(
            model_name='taskbundle',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.patient'),
        ),
    ]
