# Generated by Django 4.0.3 on 2022-06-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FHIR', '0004_claimbundle_patient_communicationbundle_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverageeligibilitybundle',
            name='response_eligibility_status',
            field=models.CharField(default='Requested', max_length=100),
        ),
    ]
