# Generated by Django 4.0.3 on 2022-06-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FHIR', '0005_coverageeligibilitybundle_response_eligibility_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverageeligibilitybundle',
            name='response_eligibility_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='coverageeligibilitybundle',
            name='response_eligibility_error',
            field=models.BooleanField(default=False),
        ),
    ]
