# Generated by Django 4.0.3 on 2022-06-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FHIR', '0007_coverageeligibilitybundle_response_eligibility_error_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverageeligibilitybundle',
            name='response_eligibility_error_description',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
