# Generated by Django 4.0.3 on 2022-06-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FHIR', '0008_alter_coverageeligibilitybundle_response_eligibility_error_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverageeligibilitybundle',
            name='response_site_eligibility_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='coverageeligibilitybundle',
            name='response_site_eligibility_not_inforce',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='coverageeligibilitybundle',
            name='response_site_eligibility_not_inforce_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='coverageeligibilitybundle',
            name='response_site_eligibility_status',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
