# Generated by Django 4.0.3 on 2022-06-28 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FHIR', '0009_coverageeligibilitybundle_response_site_eligibility_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coverageeligibilitybundle',
            name='response_site_eligibility_description',
        ),
    ]
