# Generated by Django 4.0.3 on 2022-06-28 21:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FHIR', '0010_remove_coverageeligibilitybundle_response_site_eligibility_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coverageeligibilitybundle',
            name='response_site_eligibility_not_inforce_description',
        ),
        migrations.AddField(
            model_name='coverageeligibilitybundle',
            name='createdOn',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
