# Generated by Django 4.0.3 on 2022-06-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FHIR', '0011_remove_coverageeligibilitybundle_response_site_eligibility_not_inforce_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverageeligibilitybundle',
            name='response_site_eligibility_not_inforce',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='coverageeligibilitybundle',
            name='response_site_eligibility_status',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
