# Generated by Django 4.0.3 on 2022-07-02 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_management', '0004_doctor_fhir_practitioner_id_doctor_practice_code'),
        ('billing', '0025_billing_payment_cancel_bundle_and_more'),
        ('Patient', '0015_alter_patient_third_name'),
        ('FHIR', '0012_alter_coverageeligibilitybundle_response_site_eligibility_not_inforce_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practitioner_role', models.CharField(blank=True, max_length=1000, null=True)),
                ('care_team_role', models.CharField(blank=True, max_length=1000, null=True)),
                ('specialty', models.CharField(blank=True, max_length=1000, null=True)),
                ('practitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor_management.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('on_admission', models.CharField(blank=True, max_length=100, null=True)),
                ('icd_10', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.icd10')),
            ],
        ),
        migrations.CreateModel(
            name='SupportingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=1000, null=True)),
                ('reason', models.CharField(blank=True, max_length=1000, null=True)),
                ('category', models.CharField(blank=True, max_length=1000, null=True)),
                ('value', models.CharField(blank=True, max_length=1000, null=True)),
                ('code', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=1000, null=True)),
                ('code_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('quantity', models.CharField(blank=True, max_length=1000, null=True)),
                ('unit_price', models.CharField(blank=True, max_length=1000, null=True)),
                ('factor', models.CharField(blank=True, max_length=1000, null=True)),
                ('tax', models.CharField(blank=True, max_length=1000, null=True)),
                ('patient_share_p', models.CharField(blank=True, max_length=1000, null=True)),
                ('vat', models.CharField(blank=True, max_length=1000, null=True)),
                ('net', models.CharField(blank=True, max_length=1000, null=True)),
                ('patient_share', models.CharField(blank=True, max_length=1000, null=True)),
                ('payer_share', models.CharField(blank=True, max_length=1000, null=True)),
                ('start_DateTime', models.DateTimeField(blank=True, null=True)),
                ('body_site', models.CharField(blank=True, max_length=1000, null=True)),
                ('care_teams', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FHIR.careteam')),
                ('diagnoses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FHIR.diagnosisinformation')),
                ('support_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FHIR.supportinginfo')),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_team', models.ManyToManyField(blank=True, to='FHIR.careteam')),
                ('coverage_eligibility_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FHIR.coverageeligibilitybundle')),
                ('diagnosis_information', models.ManyToManyField(blank=True, to='FHIR.diagnosisinformation')),
                ('items', models.ManyToManyField(blank=True, to='FHIR.items')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.patient')),
                ('supporting_info', models.ManyToManyField(blank=True, to='FHIR.supportinginfo')),
            ],
        ),
    ]
