# Generated by Django 4.0.3 on 2022-07-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FHIR', '0013_careteam_diagnosisinformation_supportinginfo_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='care_teams',
        ),
        migrations.AddField(
            model_name='items',
            name='care_teams',
            field=models.ManyToManyField(blank=True, to='FHIR.careteam'),
        ),
        migrations.RemoveField(
            model_name='items',
            name='diagnoses',
        ),
        migrations.AddField(
            model_name='items',
            name='diagnoses',
            field=models.ManyToManyField(blank=True, to='FHIR.diagnosisinformation'),
        ),
        migrations.RemoveField(
            model_name='items',
            name='support_info',
        ),
        migrations.AddField(
            model_name='items',
            name='support_info',
            field=models.ManyToManyField(blank=True, to='FHIR.supportinginfo'),
        ),
    ]
