# Generated by Django 4.0.3 on 2022-07-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FHIR', '0014_remove_items_care_teams_items_care_teams_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverageeligibilitybundle',
            name='beneficiary_coverage_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
