# Generated by Django 4.0.3 on 2022-07-03 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FHIR', '0015_coverageeligibilitybundle_beneficiary_coverage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='preauthbundle',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FHIR.claim'),
        ),
    ]
