# Generated by Django 4.0.3 on 2022-07-03 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FHIR', '0016_preauthbundle_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimbundle',
            name='preauth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FHIR.preauthbundle'),
        ),
    ]
