# Generated by Django 4.0.3 on 2022-07-05 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FHIR', '0017_claimbundle_preauth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communicationbundle',
            name='patient',
        ),
        migrations.AddField(
            model_name='communicationbundle',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FHIR.claimbundle'),
        ),
    ]
