# Generated by Django 4.0.3 on 2022-07-05 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FHIR', '0018_remove_communicationbundle_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreconciliationbundle',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FHIR.claimbundle'),
        ),
    ]
