# Generated by Django 4.0.3 on 2022-07-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FHIR', '0021_batchrequestbundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='claim_sub_type',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='claim_type',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
