# Generated by Django 4.0.3 on 2022-07-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FHIR', '0022_claim_claim_sub_type_claim_claim_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskbundle',
            name='request_type',
            field=models.CharField(default='cancel', max_length=1000),
        ),
    ]
