# Generated by Django 4.0.2 on 2022-02-11 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Laboratory', '0001_initial'),
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PrintedReportsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SampleEntryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SiteInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100)),
                ('flags', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('significant_digit', models.CharField(max_length=100)),
                ('quant_limit', models.CharField(max_length=100)),
                ('count_level', models.CharField(max_length=100)),
                ('scriptlet', models.CharField(max_length=100)),
                ('abnormal', models.BooleanField(default=False)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('reffered_out', models.BooleanField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=1000, null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.patient')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Laboratory.availabletests')),
            ],
        ),
        migrations.CreateModel(
            name='SampleTypeTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampletype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Laboratory.sampletype')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Laboratory.availabletests')),
            ],
        ),
        migrations.CreateModel(
            name='SampleTypePanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.panel')),
                ('sampletype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Laboratory.sampletype')),
            ],
        ),
        migrations.CreateModel(
            name='ResultLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('0', '-----'), ('1', 'NUMERIC')], default='1', max_length=1)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('O', 'RATHER NOT TO SAY')], max_length=1, null=True)),
                ('age_min', models.CharField(blank=True, max_length=20, null=True)),
                ('age_max', models.CharField(blank=True, max_length=20, null=True)),
                ('normal_range_low', models.CharField(blank=True, max_length=20, null=True)),
                ('normal_range_high', models.CharField(blank=True, max_length=20, null=True)),
                ('valid_range_low', models.CharField(blank=True, max_length=20, null=True)),
                ('valid_range_high', models.CharField(blank=True, max_length=20, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Laboratory.availabletests')),
            ],
        ),
        migrations.CreateModel(
            name='PanelItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=100)),
                ('test', models.CharField(max_length=1000)),
                ('sort_order', models.CharField(max_length=1000)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.panel')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('short_name', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('street_address', models.CharField(blank=True, max_length=1000, null=True)),
                ('internet_address', models.CharField(blank=True, max_length=1000, null=True)),
                ('type', models.ManyToManyField(related_name='organization_type', to='administration.OrganizationType')),
            ],
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('entry', models.TextField(max_length=1500)),
                ('local_abbreviation', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.category')),
            ],
        ),
    ]
