# Generated by Django 4.0.3 on 2022-07-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_alter_resultlimit_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='nphies_id',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
    ]
