# Generated by Django 4.0.2 on 2022-03-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono_insurance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='identity_card_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
