# Generated by Django 4.0.3 on 2022-06-24 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono_insurance', '0002_insurance_identity_card_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurance',
            old_name='identity_card_number',
            new_name='BeneficiaryName',
        ),
        migrations.AddField(
            model_name='insurance',
            name='BeneficiaryNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='BeneficiaryType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='BeneficiaryTypeId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='DeductibleRate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='IdentityNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='InceptionDate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='InsurancePolicyExpiryDate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='MaxLimit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='PolicyHolder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='classname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='policy_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='insurancecompany',
            name='nameAr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
